### ISSUE TITLE
Sort the files displayed when you try to open a file

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#102]
I find one thing that's inconvenient when I try to open a file is that when I search up text_buffer.py, it goes to text_buffer.pyc first. It would be helpful if we could sort the files by name, and hopefully that would also fix this issue. One misleading thing right now is that when you type text_buffer.py, **text_buffer.pyc** is highlighted, but pressing enter would open **text_buffer.py**.

**Comment by dschuyler** [comment]
I just pushed a fix for the sort order. Looking at the highlighting next.

**Comment by aaxu** [comment]
Actually it looks fixed now with the latest changes. :+1:
