### ISSUE TITLE
Black rectangle on bottom right of terminal

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#104]
This shows up whenever you start up the program, but disappears once a status line message is displayed.

**Comment by dschuyler** [comment]
Hmm, I'd hope that the status line appears very quickly.
What output do you get from this command (where we is ci.py)
```$ time we --timeStartup```
Oh and what OS and terminal program?

**Comment by aaxu** [comment]
The status line does appear very quickly, but there is no message that causes it to refresh. Here is a screenshot of what I am referring to:

![image](https://user-images.githubusercontent.com/19481525/31903070-d9cd9ea6-b7db-11e7-8722-3c521d21625d.png)

Just in case, here are the startup stats:
real	0m0.431s
user	0m0.372s
sys	0m0.040s

That black rectangle stays there until a message is displayed, such as "Save changes? (yes, no, or cancel)" (ctrl_q) or "File saved." (ctrl_s).
