### ISSUE TITLE
F1 key doesn't get intercepted by ci_edit

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#112]
The terminal intercepts this signal, so it becomes impossible to get rid of the welcome message at the start of ci_program.

**Comment by dschuyler** [comment]
That's unexpected. Do the other F-Keys get to ci_edit (e.g. using the --log view to see what ci_edit sees)?
Which terminal by the way?

I'll disable it for now.

**Comment by dschuyler** [comment]
It now defaults to not showing, but can still be shown with F1. If someone can show it with F1 I'm hoping hiding it with F1 would work too.

**Comment by aaxu** [comment]
Yes, currently using Ubuntu 16.04 default terminal. I think I remember it happening in archlinux as well. F11 also doesn't appear as it should. It shows up as ch 410 KEY_RESIZE, the same key as you get if you maximize the terminal on your monitor.

**Comment by dschuyler** [comment]
Hmm, I get ```ch 265 KEYF(1)``` on iTerm2 on Mac using terminal type ```xterm-256color```.

**Comment by aaxu** [comment]
Does your terminal contain a built in help window? Linux terminals usually
display a help window when you press F1 I think.
