### ISSUE TITLE
Selection using arrow keys when opening a file

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#115]
Maybe auto-highlight the first/current file when you go to the open-window screen with CTRL_O. We can then use the up and down arrow keys for selecting a file. When a file is selected, its name should appear in the bottom text box automatically (where we currently manually type it), so that pressing enter will open the corresponding file.

**Comment by dschuyler** [comment]
I've started on a file manager window to help with this (just an fyi)

**Comment by dschuyler** [comment]
Opening a file should now work with mouse clicking on the file or by up/down arrow keys to select file.
