### ISSUE TITLE
Opening the previous directory

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#117]
Was it intended for "." to have the functionality of ".."? Currently "." goes to the parent directory, ".." goes back 2 directories, and "..." is invalid so it brings u back to your current directory.

**Comment by aaxu** [comment]
Ah I actually see that this is because the '/' automatically opens the current directory, so you have to do this to account for that. That's kind of confusing, especially if you want to open a hidden file that starts with "."

Would it be better to just treat "." as a regular character, and only open directory when we see "../"? This should make it more consistent since I think we only open directories when we see the slash.

**Comment by dschuyler** [comment]
Thanks! Please give the fix a try.
