### ISSUE TITLE
Misspelling highlighting bug

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#131]
Not really sure how to describe this bug at the moment, but here's a gif of it happening.

![mispelling_bug](https://user-images.githubusercontent.com/19481525/34329854-ffd58982-e8c4-11e7-9e8e-5288159f56be.gif)

**Comment by dschuyler** [comment]
I'm having trouble reproducing this (and I'd like to fix it).
Was this a new file?
Was the file extension .py or something else?
Is there a chance there is non-printing bytes in file?

It looks like the parser results don't match the text.

**Comment by aaxu** [comment]
Open up app/ci_program.py and put the cursor at the beginning of the first import statement. Start typing and the problem should be reproduced.

**Comment by dschuyler** [comment]
Sadly, I still haven't been able to reproduce this.

**Comment by aaxu** [comment]
Ahh sorry, I was playing around with the branches and caused this issue to occur. Master should not experience this, and I've fixed it in my prs as well. Sorry for the confusion!
