### ISSUE TITLE
Add a high-level description to this repo

### ISSUE THREAD

**Issue by mbrukman** [google/ci_edit#134]
This repo is missing a high-level description, so it's hard to tell what it is or does without clicking through when it appears in a list of repos, e.g., when someone stars or forks it, when it's recommended or appears in a trending list.

![google-ci_edit-header](https://user-images.githubusercontent.com/4074659/34397436-1b042a0c-eb44-11e7-9a1f-f2f44aaaa9fa.png)

It would be helpful to add a description to help folks understand more about the repo to let them know whether they should click through to see more details about the project.

**Comment by dschuyler** [comment]
Thank you for the tip!
