### ISSUE TITLE
Cannot save file somewhere (like in ~/ or ../)

### ISSUE THREAD

**Issue by vitalkanev** [google/ci_edit#152]
When I open `./ci.py` with **no arguments** and save file somewhere out of my working dir, `ci` gives the the following error:

![_2018-02-13_16-56-18](https://user-images.githubusercontent.com/18398761/36153297-dd679254-10de-11e8-9a34-b96e1f93458b.png)

It does not work it the mentioned mode too.

**Comment by aaxu** [comment]
How did you save the file outside of your working directory? I tried saving the file as `../file_name` and it worked.

**Comment by aaxu** [comment]
Oh I see, giving the absolute path causes this error.

**Comment by dschuyler** [comment]
Thanks for the bug report!

**Comment by dschuyler** [comment]
(it should be fixed now)
