### ISSUE TITLE
Options window issues

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#170]
This concerns the window that appears when you press CTRL_F and then TAB to open the options window of the find window.

* If you press tab until an option is highlighted and press escape, the program will crash.
* If you click on the inputWindow text buffer while the optionsWindow is shown, it will hide itself by going blank. However, it should disappear, or else it will leave a huge white gap on the bottom of the window.
When pressing CTRL_F again, it should reappear along with the find window (which it currently does)
* Make tabbing wrap around the options and the find/replace lines, so after checking whatever options we want, the next tab will bring us back to the "find" area. This would also require us to change the way to hide the options window again, since I think it is currently shift+tab while at the "find" area.

**Comment by dschuyler** [comment]
I made tab/back-tab go in a loop. Let me know what you think.

**Comment by aaxu** [comment]
Sorry for the lack of response. I've tested it out a bit and it's a lot better now, since I don't have to worry about accidentally crashing my file :+1:

**Comment by aaxu** [comment]
Not sure if there's a way to collapse the options window, but I'm for just leaving it always showing, since sometimes I accidentally have ignoreCase OFF, and I'm not sure why I can't find a specific string in the document until I open the options window.
