### ISSUE TITLE
support python 3.x

### ISSUE THREAD

**Issue by hgoldfish** [google/ci_edit#173]
The traceback:

goldfish@nas ~/w/ci_edit> python3 ./ci.py
Traceback (most recent call last):
  File "./ci.py", line 32, in <module>
    import app.ci_program
  File "/home/goldfish/workon/ci_edit/app/ci_program.py", line 36, in <module>
    import app.history
  File "/home/goldfish/workon/ci_edit/app/history.py", line 33, in <module>
    import app.prefs
  File "/home/goldfish/workon/ci_edit/app/prefs.py", line 201, in <module>
    app.log.startup('prefs.py import time', time.time() - importStartTime)
  File "/home/goldfish/workon/ci_edit/app/log.py", line 141, in startup
    channel('startup', *args)
  File "/home/goldfish/workon/ci_edit/app/log.py", line 69, in channel
    lines = parseLines(inspect.stack()[2], channel, *args)
  File "/home/goldfish/workon/ci_edit/app/log.py", line 52, in parseLines
    prior = unicode(i)
NameError: name 'unicode' is not defined

**Comment by dschuyler** [comment]
Thanks, I've started working on this, but it will take some time.

**Comment by dschuyler** [comment]
Progress:
ci_edit can now startup with Python3. This is still very new and likely has bugs. If anyone would like to file bugs against ci_edit with Python3, feel free to do so. I don't recommend ci_edit with Python3 for serious work at this time (other than to hunt for bugs).

**Comment by aaxu** [comment]
Tried to run the program on python 3, but am getting a whole bunch of import errors. Are we still planning to move the program to be compatible towards python 3.7+ at the moment? We may need a section in each file to resolve imports depending on the python version the program was started with.

**Comment by dschuyler** [comment]
I expect that Python 2 support will be dropped at some point. I've been running tests with both versions using `tools/full_test` (which also tests single and multi-threaded use).

I just pushed a change to default to Python 3.

**Comment by dschuyler** [comment]
I'm declaring Python 3 supported. I'm closing this enhancement. If any issues are found they will be 'bugs'.
