### ISSUE TITLE
Executing full_test when inside tools directory gives error

### ISSUE THREAD

**Issue by sauravchirania** [google/ci_edit#183]
When I am in the main directory of ci_edit and run full_test using `./tools/full_test` it starts to run the tests but if I go inside the tools directory and then run full_test using `./full_test`, it gives the following error:

![ci_edit bug2](https://user-images.githubusercontent.com/30934283/50425633-4a405e00-08a1-11e9-95ee-1f735dd70164.JPG)

Is this expected behavior or a work in progress or a bug?

**Comment by dschuyler** [comment]
That's a bug and a wip. Thanks!
