### ISSUE TITLE
AttributeError: module 'profile' has no attribute 'run'

### ISSUE THREAD

**Issue by Navan0** [google/ci_edit#192]
Traceback (most recent call last):
  File "/usr/local/bin/y", line 35, in <module>
    import app.ci_program
  File "/opt/ci_edit/app/ci_program.py", line 24, in <module>
    import cProfile
  File "/usr/lib/python3.6/cProfile.py", line 22, in <module>
    run.__doc__ = _pyprofile.run.__doc__
AttributeError: module 'profile' has no attribute 'run'

**Comment by dschuyler** [comment]
Thanks for reporting this. I normally test with Python 2.7.10 and 3.7. I downloaded Python 3.6.8 and tried that but didn't see an issue. 

Please paste the output from 
$ python3 --version
into this bug so that we can see the specific 3.6 version and which platform this is happening on.

Also, consider trying Python 3.7 to see if the problem happens in that version.

**Comment by Navan0** [comment]
It's python 3.6.7

**Comment by gennad** [comment]
Do we need profiling of programs for regular users at all? Maybe add some flag like "--dev" to enable profiling?

**Comment by dschuyler** [comment]
@gennad, sounds good.
I'm a bit concerned that the Python install on @Navan0 's machine is damaged(?). While @gennad is correct about not needing this code, it should still work without crashing afaik.

**Comment by Navan0** [comment]
hmm let me reinstall and check

**Comment by billtubbs** [comment]
I thought I had this problem.  Then I realised it's because I had created a script called `profile.py` to run the profile!   (This causes `AttributeError: module 'cProfile' has no attribute 'run'`).  Hope that helps!

**Comment by dschuyler** [comment]
Good to know!

Where was the profile.py created? (Was it in the ci_edit directory?)

**Comment by billtubbs** [comment]
It was in the current working directory - the profile.py script was the script I was actually running which did some setup and called the module which had the function I wanted to profile.  Just a classic case of don't give your script the same name as a Python package in your path...

**Comment by dschuyler** [comment]
Thanks again. Since it's been awhile since Navan0's report and the description from billtubbs seems reasonable, I'll close this (assigned to billtubbs to credit billtubbs).

**Comment by Abhihugar** [comment]
import cProfile to run

**Comment by Abhihugar** [comment]
it has run attribute

**Comment by Abhihugar** [comment]
import cProfile
import re

for i in range(5):
    print(pr.calibrate(10000))
    a=cProfile.run('re.compile("Hello")')
    print(a)
