### ISSUE TITLE
Bug: Stats line shown twice

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#2]
When you drag the bottom of the terminal upward (must be done somewhat slowly) to make the window smaller, the stats line at the bottom gets shown twice. 

![image](https://user-images.githubusercontent.com/19481525/26942672-c665f044-4c37-11e7-8df1-969594be5f35.png)

**Comment by dschuyler** [comment]
Thanks for reporting bug number one!

This should be fixed in b23 (for 'build 23') which is now in the 'release' branch. (It's also on the 'master' branch, but that's under active development, while 'release' is more stable).
