### ISSUE TITLE
'str' object has no attribute 'decode' 

### ISSUE THREAD

**Issue by Ghaker** [google/ci_edit#200]
python3 --version
Python 3.7.3

**Comment by Ghaker** [comment]
I edit ci.py use python not python3, and then I can input Chinese.
but It can not support Chinese perfectly.
![image](https://user-images.githubusercontent.com/5178764/56540762-40eba780-659c-11e9-8898-1e39b01ac1af.png)
The cursor is not at correct position.

**Comment by dschuyler** [comment]
I made a fix for moving the cursor left and right over double wide characters (such as Chinese characters). I suspect that there will be other related bugs. Please let me know!

**Comment by Ghaker** [comment]
first, python3 can not support Chinese ,when I input Chinese(input 'n' 'i' '<space>') ,It will crash,so I used python2,my environment
<img width="593" alt="图片" src="https://user-images.githubusercontent.com/5178764/56857488-d32aeb80-69a0-11e9-8275-64f343343c4e.png">
 
<img width="570" alt="图片" src="https://user-images.githubusercontent.com/5178764/56857464-847d5180-69a0-11e9-8a28-be7c53befc54.png">

usually,almost Chinese use  [sougou inputting method;](https://pinyin.sogou.com/mac/),and I use mac native inputting method
<img width="668" alt="图片" src="https://user-images.githubusercontent.com/5178764/56857555-84ca1c80-69a1-11e9-80e3-91d1e50aab4e.png">
It seems to be the same.I input 'ni<space>hao<space>' . I can't see character '你'.
<img width="570" alt="图片" src="https://user-images.githubusercontent.com/5178764/56857601-31a49980-69a2-11e9-8c7c-048b6b74732e.png">
And I need  entering <delete> twice.

**Comment by Ghaker** [comment]
@dschuyler
