### ISSUE TITLE
Cannot open file. Ubuntu 18.04

### ISSUE THREAD

**Issue by rohit1607** [google/ci_edit#218]
Super sorry, something went very wrong.
Please create a New Issue and paste this info there.

Traceback (most recent call last):
  File "/opt/ci_edit/app/ci_program.py", line 557, in wrapped_ci
    prg.run()
  File "/opt/ci_edit/app/ci_program.py", line 494, in run
    self.commandLoop()
  File "/opt/ci_edit/app/ci_program.py", line 200, in commandLoop
    self.refresh(drawList, cursor, frameCmdCount)
  File "/opt/ci_edit/app/ci_program.py", line 433, in refresh
    curses.curs_set(0)  # Hide cursor.
_curses.error: curs_set() returned ERR

**Comment by dschuyler** [comment]
Thank you for the bug report!

Can you tell me more about it, such as:
- what platform did this happen on (windows, mac, linux)?
- did it happen when starting the program or did it happen later?
- does this happen often or did it just happen once?
- is it a particular file?

If you run ci_edit with --version, what does it say (copy/paste to this bug maybe).

**Comment by rohit1607** [comment]
Hi Dave !
It seems that I am able to open files now. I guess things went to normal after I restarted my system, maybe.

In any case, I’ll list down answers to your queries:
1.	Linux- Ubuntu 18.04
2.	It had happened while starting the program to edit a file
3.	It just happened once. As in the first couple of times, until I restarted my machine.
4.	No. It was not opening any file.
5.	The following comes up on running ci_edit --version

>   Version (build iteration): v50
>   Within Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
> [GCC 7.3.0]
>   See LICENSE for license information
>   See readme.md for an introduction
>   Both files may be found in "/opt/ci_edit"
>   Please give the gift of feedback and bug reports at
>     https://github.com/google/ci_edit/issues

**Comment by dschuyler** [comment]
I'm glad it's working. Please let me know if something else comes up :)
