### ISSUE TITLE
CTRL + SHIFT + UP error

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#25]
There is an assertion error in doMoveLines inside the Mutator class. I think it's because the **to** variable is changed before the assertion checked, thus failing the assertion.

The error can be reproduced as follows:
1. Start up the text editor with any document with more than 2 lines
2. Make any selection such that the top of the selection is not on the very first line
3. Perform CTRL + SHIFT + UP and the program will crash.

**Comment by dschuyler** [comment]
I found that step #2 show the problem with line selection, but not with character selection (just and fyi)

**Comment by aaxu** [comment]
Try this:
1. Start up an empty document
2. type in 'aa'
3. Hit the enter key
4. type in 'bb'
5. Shift + Left to select the last 'b'
6. CTRL_SHIFT_UP
