### ISSUE TITLE
Resizing terminal after starting the program

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#37]
This just causes a whole bunch of errors. I'll try to list out each one.

* Drag the window so that you make the **height** smaller. Then hold enter and the program will break once the cursor goes past the terminal screen.
* Drag the window so that the **width** is smaller. This will cause a grey area to expand and block the text that is on the screen.
* Increase the size of the window. The size of the **window objects** (like the text buffer, line numbers, etc) will not increase with the size of the window.

**Comment by aaxu** [comment]
Currently working on this issue..

**Comment by dschuyler** [comment]
Thanks for looking at this. I think I broke handleScreenResize, which I just updated. Does that change help?

**Comment by dschuyler** [comment]
(On the plus side, I got the screen rendering to go significantly faster while breaking the resizing)
