### ISSUE TITLE
Entire window is grey

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#5]
The entire window starts out grey. Every character you type turns the grey spot into a black spot. This issue was caused after one of the recent commits to the master branch.

![image](https://user-images.githubusercontent.com/19481525/27098871-dabee7a4-502d-11e7-922f-77214e787d9b.png)

**Comment by dschuyler** [comment]
I thought I'd fixed that. If it's still happening, please let me know the OS and terminal being used so I can try to reproduce it.

**Comment by aaxu** [comment]
It's happening on the latest version of Arch Linux. I haven't tested it yet on my Windows and Ubuntu 16.04 systems yet as I don't have access to it until later today.

**Comment by dschuyler** [comment]
I'm not seeing it on Ubuntu or Mac (iterm2). I tried changing the palette of colors. Please let me know if it looks better now.

**Comment by aaxu** [comment]
This is what I'm seeing from terminal and I reproduced this on Ubuntu 16.04 and Arch linux both on their default terminals. 

Note: I discovered that this only appears when the terminal the terminal sizes passes a certain dimension, so these first two images are what happens when I have my terminal maximized.
![image](https://user-images.githubusercontent.com/19481525/27119671-99439c8a-5095-11e7-9186-3592f6728b1a.png)
![image](https://user-images.githubusercontent.com/19481525/27119679-9e9961f6-5095-11e7-8a8e-6bbdaf825636.png)


These next two images are when the terminal is under some dimension which I'm guessing is the correct behavior:
![image](https://user-images.githubusercontent.com/19481525/27119862-6278cd8c-5096-11e7-880d-1e9e84dfa358.png)

**Comment by dschuyler** [comment]
Okay, thanks again. I made another change / attempt to fix this. It's on the master branch.

**Comment by aaxu** [comment]
This is what I'm getting now.

From a terminal emulator (which comes as default on Arch):

![image](https://user-images.githubusercontent.com/19481525/27196335-e09e64a0-51be-11e7-8c5c-dd271e73e699.png)

From gnome-terminal downloaded on Arch:

![image](https://user-images.githubusercontent.com/19481525/27196391-1909de1e-51bf-11e7-8eac-577996b806a7.png)

The default background color for the first one is black and the color for the second one is white, so the find prompt should be correctly displaying the right color. Everything is still this grayish color, although it is cleaner than before this fix.

**Comment by dschuyler** [comment]
Thanks again. I've been trying to get a white page with a grey surround. I've made further changes, is it improved?

**Comment by dschuyler** [comment]
I'm also open to feedback on whether the end result (once it works) is good or not.

**Comment by aaxu** [comment]
Hmm I'm actually getting a grey surround and lines that have text are white now. It seems a lot better now, but i'm not sure if it's still what you intended. 

![image](https://user-images.githubusercontent.com/19481525/27513830-bb851402-592a-11e7-9259-5cb80235758b.png)

**Comment by dschuyler** [comment]
Thanks!

Okay, so now that it's showing up the same for us both: is it a good scheme?

The idea was to change from highlighting long lines (greater than 80 cols) with a single color (which loses the syntax highlighting) to a more subtle though clear indicator, such as just changing the background color (which still shows the syntax highlighting).

That lead me to thinking of the  'page' as a white rectangle with long lines 'going off the page'. I think it looks nice (or nicer) in a long document (at least it looks more clear to me that it's going past the end of the page as an fyi to the user (rather than a rendering glitch).

In the screen shot above, that looks a bit like a bug or drawing glitch. Maybe it's because the after-area (past the last line) is the same grey. I wonder if it would convey the idea better if the after-area were the color of the status bar or the line-number column.

**Comment by aaxu** [comment]
Hm... yeah I was thinking what if we just made all the columns before column 80 as one solid color and all the columns after that as some other color? 

As for color schemes, I was thinking it would be nice if we had a color scheme that was nice on the eyes, but still had a fair amount of contrast. I think the current white we have now is going to be hard on the eyes after a certain period of time. What about something like whitish-grey text on darkish-grey background? Although, I don't know what to make the other colors since we have quite a few of them.

**Comment by dschuyler** [comment]
I agree, I'd like to have different color schemes and an easy way for users to create their own.

Trivia: I turn down the brightness on my screen so the white is more muted. I'm not saying that others should do so, just explaining how I get by for longish periods of time with a white background.

**Comment by aaxu** [comment]
Hmm yeah okay I guess that works. What about we implement a few sets of popular color schemes? White on black, black on white, classic ubuntu terminal, maybe a whiteish color on dark grey.

**Comment by dschuyler** [comment]
I made a new Enhancement issue to track the color schemes.
