### ISSUE TITLE
Redo after save not working

### ISSUE THREAD

**Issue by dschuyler** [google/ci_edit#57]
in a file, type
```
A
B
```
then undo so that only A is shown
Save
Press ctrl+y to redo

Problem: B does not reappear.

**Comment by dschuyler** [comment]
The 'cc' compound change was messing up the redoChain after a save (well, really after removing trailing blank space which happened on save).

**Comment by aaxu** [comment]
What was the fix for this issue? Are we going to just leave it so that removing trailing spaces will also truncate the redo chain?
