### ISSUE TITLE
Pasting from clipboard

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#68]
Make terminal paste things from clipboard (that you copied outside of the program) be able to paste inside the program with CTRL+V, or the paste function.

Currently, things copied to clipboard can be pasted inside the program with CTRL+SHIFT+V which is how you typically paste in a terminal. However, the format may sometimes be incorrect. Also, it is not possible to copy something from the program to the clipboard and paste it outside of the program.

**Comment by dschuyler** [comment]
ctrl + v should work (or, err, it works on Ubuntu and OSX for me).
Is it not working on a particular platform/terminal?

**Comment by aaxu** [comment]
I'm using the default terminal in Ubuntu 16.04

**Comment by dschuyler** [comment]
Suggestions to track it down:

Try running with --log to see what key value is sent for ctrl+v (to see if we're getting the key).

Look in (add logging printout) in third_party/pyperclip/*.py to see if copy/paste handlers are being set up. (especially in ```third_party/pyperclip/__init__.py```)

If you are able to workout what the issue is, it would be *great* to find out how to address it for other users (like maybe we can tell them they're missing xclip or kipper or similar and suggest something to fix it).

**Comment by aaxu** [comment]
So the issue with my terminal is that when it sees **CTRL_SHIFT_V**, whatever is actually on my clipboard in the OS will be entered as a character. So for example, if I have the word **hi there** copied on my clipboard, when I enter the program and use **CTRL_SHIFT_V**, curses.getch() will get 'h', then 'i', then 't' etc until everything has been handled (at least I think this is the case from testing). This makes it difficult to handle because I think it's being handled by the terminal.

Oddly enough, CTRL_SHIFT_C doesn't seem to count as a character and doesn't do anything. It doesn't  even show a character code when I tried catching it.

Not really sure about a solution for this..

**Comment by dschuyler** [comment]
How about ctrl+v, will that paste the text as a unit? It should. That's the intended way to paste without the formatting getting misunderstood.

The ctrl+shift+v is working as expected, though I have considered improving it. There's no 'great' way to handle that. The hackey ways I've thought of involve timing the input and reasoning that at 120+ words-per-minute is a paste and not someone typing. But that's not foolproof on a remote connection.

**Comment by aaxu** [comment]
Yeah CTRL + V works properly. It's just that you can't copy anything from outside the program and paste it inside the program since you're not directly accessing the OS's clipboard from the program.

There is a bug with the CTRL_SHIFT_V though. If you have a block of text like this:

```
test:
test
```

and copy those two lines and paste it into terminal with CTRL_SHIFT_V, the second line will be auto indented, whereas if you typed and copied the same line in ci_edit and paste it with CTRL_V, it won't be indented.

**Comment by dschuyler** [comment]
Is this a remove connection (like ssh)? pyperclip should try to connect to the OS clipboard (or pasteboard), but on a remote connection, that may not be accessible.

Yes on the CTRL_SHIFT_V, that's the problem I was alluding to (your example is much clearer that my explanation, thanks).

**Comment by aaxu** [comment]
No, its not a remote connection. Ubuntu is my host OS. Ill have to try on other systems and OS later and see if it persists.

**Comment by dschuyler** [comment]
This also looks like it might be useful:
http://www.xfree86.org/current/ctlseqs.html#Bracketed%20Paste%20Mode
Apparently Bracketed Paste Mode is something to help detect a paste into the terminal.

**Comment by aaxu** [comment]
Ohh thats cool.

Maybe we can use the subprocess module and call some commands to enable it and turn it off when we exit the program.

Here is what I found so far from a source [https://cirw.in/blog/bracketed-paste](url) :+1: 

> 1. Enable bracketed paste: printf "\e[?2004h"
> 2. Wait for paste to start: you'll see \e[200~ on STDIN.
> 3. Wait for paste to stop: you'll see \e[201~ on STDIN.
> 4. Disable bracketed paste: printf "\e[?2004l"

I tested this on my terminal (default gnome-terminal 3.18.3 in ubuntu 16.04), and when I paste, the clipboard text is surrounded by 0~*pastedText*1~ . Not sure why this is happening, but maybe we'll just have to check these two and see if that works for most cases? Need testing done by more people on different OS and terminals though in order to gather more data.

**Comment by dschuyler** [comment]
fyi, I've started working on this.

**Comment by dschuyler** [comment]
I put up a rough implementation. Does it work for you?

**Comment by aaxu** [comment]
Yeah, it's great! Works in and out of the program properly :+1:
