### ISSUE TITLE
Index error occurs when trying to type on line 2

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#73]
Open any file and try to type on the 2nd line in the document. An index error should occur and the program will crash.

**Comment by aaxu** [comment]
Seems to be caused by parse() function in `parser.py`. if beginRow = 1, then you decrement it and the line 
`self.parserNodes = self.parserNodes[:self.rows[beginRow]]` sets self.parserNodes to an empty list, but you don't check for this condition in `__buildGrammarList`. I'll leave this up to you for now since I don't want to mess up your implementation, since I don't fully understand how it works yet.

**Comment by dschuyler** [comment]
Thanks for the report!
