### ISSUE TITLE
Program crashes on other systems.

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#76]
I tried running the program on another system, and it seems to error out. The program is crashing because it's trying to import bookmarks.py which doesn't exist anymore, but I'm not sure why it doesn't error on our current systems. Do you have any idea why this occurs?

**Comment by dschuyler** [comment]
Check for an old .pyc or .pyo file.

**Comment by dschuyler** [comment]
or the import app.bookmarks on line 24 of app/ci_program.py

**Comment by aaxu** [comment]
oh, that makes sense.

**Comment by dschuyler** [comment]
I've removed it. I'll close this -- please let me know if it's not fixed.
