### ISSUE TITLE
Exception occurs when closing file.

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#78]
This bug only sometimes happens, but it seems to be reproducible if you keep trying for a little while.

### Steps: 
* `python ci.py ci.py` (I don't think file matters, since it also happened when I tried using install.sh). This error actually seems to occur more if no file is specified, so `python ci.py`
* CTRL_Q

![image](https://user-images.githubusercontent.com/19481525/31347150-3bffeb7c-acd0-11e7-93f1-6f2acef0a2e3.png)

**Comment by dschuyler** [comment]
The background.py has been changing a lot recently. Is it still happening today? (I tried it several times with the latest code and didn't see it).

**Comment by aaxu** [comment]
With the new updated code, I got this on the first run of the program.
![image](https://user-images.githubusercontent.com/19481525/31351444-f3f96abe-acdf-11e7-9bab-c60abbc32139.png)
It seems to only happen when generating the .pyc file, so subsequent runs won't cause this warning to appear.

Then, once in a while, this message will appear when exiting.
![image](https://user-images.githubusercontent.com/19481525/31351508-3881d2fc-ace0-11e7-93d6-e8e0d77a72fe.png)
No idea where the stack trace went..

**Comment by dschuyler** [comment]
Thanks!

This should now be fixed.
