### ISSUE TITLE
Inconsistent highlighting of words

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#81]
![image](https://user-images.githubusercontent.com/19481525/31367112-ef28e74a-ad29-11e7-959d-6af18da7772d.png)

Seems to be having some weird interaction with the 80 char line.

**Comment by dschuyler** [comment]
Yeah, the white background and grey background are two separate draw calls and the spell checking on the last line was starting from the beginning of the grey part. So it's saying the 'ing' is a misspelled word.
