### ISSUE TITLE
Weird cursor behavior

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#82]
I'm not really sure how to describe this, but I'll make a short gif here..
![ci_edit_bug](https://user-images.githubusercontent.com/19481525/31367210-9803acc4-ad2a-11e7-9883-950587568565.gif)

At the beginning, I'm demonstrating that the cursor is working as intended. However, after I insert a space after 'the', that brownish box appears and seems to follow my cursor. Near the end it also gets stuck near the 80 character line.

**Comment by dschuyler** [comment]
Thanks for all these bug reports
