### ISSUE TITLE
Error when saving. File gets corrupted.

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#86]
## Steps to reproduce
* Create a new file, add characters so it has at least 1 character in the file and then save.
* Re-open the file
* Select all the characters in the file (CTRL_A by default)
* Type anything to replace all the characters
* Save -> This will cause an error message to appear saying that the file did not save properly.
* Quit the program with CTRL_Q and press N to not save the file.
* Reopen the file. You should now see a corrupted file. It may or may not even open in the program properly, or the offset/data in the file is different from expected.

**Comment by dschuyler** [comment]
Hmm, I need to watch for mixing ascii and unicode strings. Thanks for finding this!
