### ISSUE TITLE
Undo into saved undo breaks redo chain

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#88]
Ways to emulate this:
* Copy anything into your clipboard.
* Create a new file.
* Paste consecutively three times
* Save
* Reopen file
* Hold undo
* Weird behaviors will happen. The best behavior I've seen is that the redo chain just stops allowing you to undo, even when there is supposed to be more stuff. (ie, doing the steps above should leave one copy paste in your program). The worst behavior I've seen is where the views all freeze. I think you can still exit with CTRL_Q + y/n, but the visible screen looks like it froze. Another behavior is where the screen looks frozen, but once u click the text buffer, changes get updated as if the screen refreshed.

**Comment by dschuyler** [comment]
I'm able to repro it.
running we --clearHistory will make the issue not happen (though that also removes the history -- this is not a suggestion, just a point of data).
I tried going back dozens of git commits and the issue persist.

**Comment by dschuyler** [comment]
As a stop-gap (not a real solution) I made "saveUndo" a preference setting and default it to False.
So a new user won't see this issue, but they also wont have save/restore undo.
