### ISSUE TITLE
Incorrect word is half highlighted in red

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#90]
![image](https://user-images.githubusercontent.com/19481525/31459315-a847741e-ae77-11e7-86e3-ede7779062ed.png)

**Comment by aaxu** [comment]
It looks like this is happening because it thinks that words are separated based on the capitalization of the characters rather than the spacing. Something like `split a long word into multiple words by grabbing the first capital letter that appears before lowercase characters`

for instance:
HELLOthere would split into 'HELL' and 'OTHERE'.
HELLOthereNOTaword would become 'HELL', 'Othere', 'NO', 'Taword'
HELLOthereNEWWORD would become 'HELL', 'Othere', 'NEWWORD'

**Comment by dschuyler** [comment]
100% right.

It's expecting CamelCaseCombinedWords.

So it sees URIs and URLs as UR Is and UR ls.

**Comment by aaxu** [comment]
Do you think we should highlight camelCase words? I think that in most cases, camel case would be used by programmers and many times, variable names aren't whole words. Maybe for camelCase, we can see if it matches any of the already existing camelCase words in the document so it would be like a variable name check rather than a grammer check?

**Comment by aaxu** [comment]
Update: found another bug that doesn't look like camel case.

![highlight_bug](https://user-images.githubusercontent.com/19481525/31683083-c150dd20-b330-11e7-9e6e-ec05c4c4ced5.gif)

**Comment by aaxu** [comment]
More weird interactions with highlighting.

![highlight_bug_2](https://user-images.githubusercontent.com/19481525/31683662-6ca7c8f4-b332-11e7-8249-370d64ea31b0.gif)

**Comment by dschuyler** [comment]
The last two comments showing weird spell checking behavior on the last line should now be fixed.

**Comment by aaxu** [comment]
Now, when you open/create a new file from the program, highlights will not work until you save and reopen.

**Comment by dschuyler** [comment]
Was that in the last (or only) line in the file? There was a problem with doing highlighting on the last line of the file that I recently fixed.

**Comment by aaxu** [comment]
It is happening in the entire file. A newly created file will not have any highlighting at all until you save and reopen.

**Comment by dschuyler** [comment]
I'm going to fix the initial bug report and close this. Please open a different issue if there's more to be fixed :)
